MAX_NAME_LENGTH = 200
MAX_COLOR_LENGTH = 7
MAX_SLUG_LENGTH = 200
MAX_MEASUREMENT_UNIT_LENGTH = 200
HEX_COLOR_REGEX = '^#[0-9a-fA-F]{6}$'
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_QUANTITY = 1
