version: '3.3'

volumes:
  pg_data:
  static:
  media:
  frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: off1ght/foodgram_backend/
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    env_file: .env
    image: off1ght/foodgram_frontend
    volumes:
      - frontend:/app/build/
    restart: always
  
  gateway:
    image: off1ght/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - frontend
    restart: always
  