# Generated by Django 4.2.2 on 2023-09-21 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_shoppinglist_shoppingcart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
