# Generated by Django 4.2.2 on 2023-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_rename_quantity_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
